CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "Cities" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text,
    CONSTRAINT "PK_Cities" PRIMARY KEY ("Id")
);

CREATE TABLE "Persons" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FirstName" text,
    "LastName" text,
    "Gender" integer NOT NULL,
    "PersonalNumber" text,
    "BirthDate" timestamp with time zone NOT NULL,
    "CityId" integer NOT NULL,
    "ImageUrl" text,
    CONSTRAINT "PK_Persons" PRIMARY KEY ("Id")
);

CREATE TABLE "PersonRelations" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Type" integer NOT NULL,
    "PersonId" integer NOT NULL,
    "RelatedPersonId" integer NOT NULL,
    CONSTRAINT "PK_PersonRelations" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PersonRelations_Persons_PersonId" FOREIGN KEY ("PersonId") REFERENCES "Persons" ("Id") ON DELETE CASCADE
);

CREATE TABLE "PhoneNumbers" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Type" integer NOT NULL,
    "Number" text,
    "PersonId" integer,
    CONSTRAINT "PK_PhoneNumbers" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PhoneNumbers_Persons_PersonId" FOREIGN KEY ("PersonId") REFERENCES "Persons" ("Id")
);

CREATE INDEX "IX_PersonRelations_PersonId" ON "PersonRelations" ("PersonId");

CREATE INDEX "IX_PhoneNumbers_PersonId" ON "PhoneNumbers" ("PersonId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251027094414_InitialCreate', '9.0.10');

ALTER TABLE "PhoneNumbers" DROP CONSTRAINT "FK_PhoneNumbers_Persons_PersonId";

DROP INDEX "IX_PersonRelations_PersonId";

ALTER TABLE "PersonRelations" RENAME COLUMN "Type" TO "RelationType";

UPDATE "PhoneNumbers" SET "PersonId" = 0 WHERE "PersonId" IS NULL;
ALTER TABLE "PhoneNumbers" ALTER COLUMN "PersonId" SET NOT NULL;
ALTER TABLE "PhoneNumbers" ALTER COLUMN "PersonId" SET DEFAULT 0;

ALTER TABLE "PhoneNumbers" ALTER COLUMN "Number" TYPE character varying(50);
UPDATE "PhoneNumbers" SET "Number" = '' WHERE "Number" IS NULL;
ALTER TABLE "PhoneNumbers" ALTER COLUMN "Number" SET NOT NULL;
ALTER TABLE "PhoneNumbers" ALTER COLUMN "Number" SET DEFAULT '';

ALTER TABLE "Persons" ALTER COLUMN "PersonalNumber" TYPE character varying(11);
UPDATE "Persons" SET "PersonalNumber" = '' WHERE "PersonalNumber" IS NULL;
ALTER TABLE "Persons" ALTER COLUMN "PersonalNumber" SET NOT NULL;
ALTER TABLE "Persons" ALTER COLUMN "PersonalNumber" SET DEFAULT '';

ALTER TABLE "Persons" ALTER COLUMN "LastName" TYPE character varying(50);
UPDATE "Persons" SET "LastName" = '' WHERE "LastName" IS NULL;
ALTER TABLE "Persons" ALTER COLUMN "LastName" SET NOT NULL;
ALTER TABLE "Persons" ALTER COLUMN "LastName" SET DEFAULT '';

ALTER TABLE "Persons" ALTER COLUMN "ImageUrl" TYPE character varying(500);

ALTER TABLE "Persons" ALTER COLUMN "FirstName" TYPE character varying(50);
UPDATE "Persons" SET "FirstName" = '' WHERE "FirstName" IS NULL;
ALTER TABLE "Persons" ALTER COLUMN "FirstName" SET NOT NULL;
ALTER TABLE "Persons" ALTER COLUMN "FirstName" SET DEFAULT '';

ALTER TABLE "Cities" ALTER COLUMN "Name" TYPE character varying(100);
UPDATE "Cities" SET "Name" = '' WHERE "Name" IS NULL;
ALTER TABLE "Cities" ALTER COLUMN "Name" SET NOT NULL;
ALTER TABLE "Cities" ALTER COLUMN "Name" SET DEFAULT '';

INSERT INTO "Cities" ("Id", "Name")
VALUES (1, 'თბილისი');
INSERT INTO "Cities" ("Id", "Name")
VALUES (2, 'ბათუმი');
INSERT INTO "Cities" ("Id", "Name")
VALUES (3, 'ქუთაისი');
INSERT INTO "Cities" ("Id", "Name")
VALUES (4, 'რუსთავი');
INSERT INTO "Cities" ("Id", "Name")
VALUES (5, 'გორი');
INSERT INTO "Cities" ("Id", "Name")
VALUES (6, 'ზუგდიდი');
INSERT INTO "Cities" ("Id", "Name")
VALUES (7, 'ფოთი');
INSERT INTO "Cities" ("Id", "Name")
VALUES (8, 'თელავი');

CREATE UNIQUE INDEX "IX_Persons_CityId" ON "Persons" ("CityId");

CREATE UNIQUE INDEX "IX_Persons_PersonalNumber" ON "Persons" ("PersonalNumber");

CREATE UNIQUE INDEX "IX_PersonRelations_PersonId_RelatedPersonId" ON "PersonRelations" ("PersonId", "RelatedPersonId");

CREATE INDEX "IX_PersonRelations_RelatedPersonId" ON "PersonRelations" ("RelatedPersonId");

CREATE UNIQUE INDEX "IX_Cities_Name" ON "Cities" ("Name");

ALTER TABLE "PersonRelations" ADD CONSTRAINT "FK_PersonRelations_Persons_RelatedPersonId" FOREIGN KEY ("RelatedPersonId") REFERENCES "Persons" ("Id") ON DELETE CASCADE;

ALTER TABLE "Persons" ADD CONSTRAINT "FK_Persons_Cities_CityId" FOREIGN KEY ("CityId") REFERENCES "Cities" ("Id") ON DELETE RESTRICT;

ALTER TABLE "PhoneNumbers" ADD CONSTRAINT "FK_PhoneNumbers_Persons_PersonId" FOREIGN KEY ("PersonId") REFERENCES "Persons" ("Id") ON DELETE CASCADE;

SELECT setval(
    pg_get_serial_sequence('"Cities"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Cities") + 1,
        nextval(pg_get_serial_sequence('"Cities"', 'Id'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251027111343_ConfigureConstraints', '9.0.10');

ALTER TABLE "PersonRelations" DROP CONSTRAINT "FK_PersonRelations_Persons_RelatedPersonId";

ALTER TABLE "PersonRelations" ADD CONSTRAINT "FK_PersonRelations_Persons_RelatedPersonId" FOREIGN KEY ("RelatedPersonId") REFERENCES "Persons" ("Id") ON DELETE RESTRICT;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251027115415_UpdateConfiguration', '9.0.10');

ALTER TABLE "Persons" ADD "Status" integer NOT NULL DEFAULT 0;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251027143304_AddSatatusToPerson', '9.0.10');

DROP INDEX "IX_Persons_CityId";

CREATE INDEX "IX_Persons_CityId" ON "Persons" ("CityId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251029115905_ChangeCityProperty', '9.0.10');

COMMIT;

